GET https://fswd-part3-backend.herokuapp.com/api/persons

### also for testing 3.8
POST https://fswd-part3-backend.herokuapp.com/api/persons HTTP/1.1
Content-type: application/json

{
    "name": "Mike",
    "number": "1234567"
}

### name missing
POST https://fswd-part3-backend.herokuapp.com/api/persons HTTP/1.1
Content-type: application/json

{
    "number": "1234567"
}

### number missing
POST https://fswd-part3-backend.herokuapp.com/api/persons HTTP/1.1
Content-type: application/json

{
    "name": "Mike"
}

### name exists
POST https://fswd-part3-backend.herokuapp.com/api/persons HTTP/1.1
Content-type: application/json

{
    "name": "Arto Hellas",
    "number": "1111111"
}